### Introduction To Numpy 

#### Wait... why am I learning this again? I already know lists!

Untill now, we all know Python lists are powerful!
<ul>
    <li>They can hold collection of values</li>
    <li>They can hold different types of data</li>
    <li>We can change, add or remove the items inside of a list</li>
    </ul>
buttttt one important thing is missing.


**the ability to perform a mathematical operation over *all* the items at the same time**

Let's explore what I exactly mean by this.
We have the heights and weights of my family members right here:

In [1]:
heights = [1.73, 1.68, 1.79, 1.92, 1.50, 1.64]
weights = [90.0, 71.0, 55.0, 67.0, 99.2, 69]

If we want to calculate the BMI of each person, the fastest thing we hope that's gonna work would be the following:

In [2]:
weights/heights**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

oh oh :( Python has no idea what we're talking about. well no worries, that's why we have **Numpy**!

Numpy has its own array, which is an alternative for our regular Python lists. 
We simply call them **numpy arrays**


[in case you haven't installed numpy, run the following cell]

In [ ]:
!pip3 install numpy

In [3]:
import numpy as np

Let's *convert* our previous lists into numpy arrays and see if we can perform the one-liner in line2!

In [4]:
heights_np = np.array(heights)
heights_np

array([1.73, 1.68, 1.79, 1.92, 1.5 , 1.64])

In [5]:
type(heights_np)

numpy.ndarray

In [6]:
weights_np = np.array(weights)
weights_np

array([90. , 71. , 55. , 67. , 99.2, 69. ])

In [7]:
bmi = weights_np/heights_np**2

In [8]:
bmi

array([30.07116843, 25.15589569, 17.16550669, 18.17491319, 44.08888889,
       25.6543724 ])

**Important Note : Numpy arrays can ONLY contain ONE data-type**
- type coercion 


In [9]:
arr = [1, '2', 3]
np_arr = np.array(arr)
np_arr

array(['1', '2', '3'], dtype='<U21')

##### Sum of two numpy arrays

In [10]:
example = [1, 2, 3]
example + example

[1, 2, 3, 1, 2, 3]

In [11]:
example_np = np.array([1, 2, 3])
example_np + example_np

array([2, 4, 6])

##### Numpy Array Subsetting

In [12]:
example[1]

2

In [13]:
example_np[1]

2

In [14]:
bmi

array([30.07116843, 25.15589569, 17.16550669, 18.17491319, 44.08888889,
       25.6543724 ])

In [15]:
bmi>30

array([ True, False, False, False,  True, False])

In [16]:
bmi[bmi>30]

array([30.07116843, 44.08888889])

In [17]:
bmi[bmi<30]

array([25.15589569, 17.16550669, 18.17491319, 25.6543724 ])

### Tasks 


A list baseball has already been defined below, representing the height of some baseball players in centimeters. Can you add some code here and there to create a numpy array from it?

In [18]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]
# Import the numpy package as np
import numpy as np
# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)
# Print out type of np_baseball
np_baseball

array([180, 215, 210, 210, 188, 176, 209, 200])

In [20]:
heights_in = [72, 74, 67, 69, 66, 68, 77, 70]
# Create a numpy array from height_in: np_height_in
np_height_in = np.array(heights_in)
# Print out np_height_in
np_height_in
# Convert np_height_in to m: np_height_m
#multiply by 0.0254
np_height_m = np_height_in*0.0254
# Print np_height_m
np_height_m

array([1.8288, 1.8796, 1.7018, 1.7526, 1.6764, 1.7272, 1.9558, 1.778 ])

Use np_height_m and np_weight to calculate the BMI of each player. Use the following equation:
weight/height ** 2
Save the resulting numpy array as bmi.
Print out bmi.

In [22]:
weights = [90.0, 71.0, 120.0, 97.0, 99.2, 100, 150, 120]
weights_np = np.array(weights)
# Calculate the BMI: bmi
BMI = weights_np/np_height_m**2
# Print out bmi
BMI

array([26.90977604, 20.09682617, 41.43470082, 31.57956326, 35.29850953,
       33.52082829, 39.21411115, 37.95925959])

In [27]:
type(BMI)

numpy.ndarray

In [24]:
BMI[BMI>40]

array([41.43470082])

In [25]:
np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])

Try to interpret what happened in the last line

Can you tell which code chunk builds the exact same Python object? 

- np.array([True, 1, 2, 3, 4, False])

- np.array([4, 3, 0]) + np.array([0, 2, 2])

- np.array([1, 1, 2]) + np.array([3, 4, -1])

- np.array([0, 1, 2, 3, 4, 5])

In [26]:
np.array([1, 1, 2]) + np.array([3, 4, -1])

array([4, 5, 1])

### n dimentional Numpy Arrays

In [29]:
weight_and_height = np.array([[1.73, 1.68, 1.79, 1.92, 1.50, 1.64], [90.0, 71.0, 55.0, 67.0, 99.2, 69]])

In [30]:
weight_and_height

array([[ 1.73,  1.68,  1.79,  1.92,  1.5 ,  1.64],
       [90.  , 71.  , 55.  , 67.  , 99.2 , 69.  ]])

In [31]:
weight_and_height[0, 3]

1.92

In [32]:
weight_and_height[0][3]

1.92

In [37]:
weight_and_height[0:2, :5]

array([[ 1.73,  1.68,  1.79,  1.92,  1.5 ],
       [90.  , 71.  , 55.  , 67.  , 99.2 ]])

In [38]:
weight_and_height.shape

(2, 6)